server.port=8080

# H2 in-memory database configuration
data_source.url=jdbc:h2:mem:testdb
data_source.driverClassName=org.h2.Driver
data_source.username=sa
data_source.password=

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
